config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cams, only: [:show]

  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
    resources :jwts, only: %i[index create destroy] do
      collection do
        delete :clean_expired_jwts
      end
    end
  end

  namespace :api do
    match "me" => "application#user_info", via: :options
  end

  namespace :admin do
    root to: "home#index"

    resources :users, except: %i[destroy] do
      member do
        patch :lock
        patch :unlock
        patch :resend_confirmation_mail
        patch :resend_invitation_mail
      end
    end
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions"
  }

  devise_scope :user do
    resource :registrations,
             only: %i[new create],
             path: "users",
             path_names: { new: "sign_up" },
             controller: "users/registrations",
             as: :user_registration

    resource :invitations,
             only: %i[edit update],
             path: "users",
             controller: "users/invitations",
             as: :user_invitations
  end

  get "users", to: redirect("/users/sign_up")

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/helpers/sidebar_helper.rb
# frozen_string_literal: true

module SidebarHelper
  def collapsed_sidebar?
    cookies["sidebar_collapsed"] == "true"
  end

  def use_sidebar(name = "application")
    @_sidebar_name = name
  end

  def has_sidebar?
    @_sidebar_name.present?
  end

  def render_sidebar
    return unless has_sidebar?
    render "layouts/sidebars/#{@_sidebar_name}"
  end
end

app/views/layouts/sidebars/_accounts.html.erb
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <%= nav_item controller: 'accounts/profiles', html_options: {class: "nav-item"} do %>
        <%= link_to account_profile_path, class: "nav-link" do %>
          <i class="nav-icon fas fa-user-circle"></i>
          <%= t("layouts.sidebar.accounts.profile") %>
        <% end %>
      <% end %>
      <%= nav_item controller: 'accounts/passwords', html_options: {class: "nav-item"} do %>
        <%= link_to account_password_path, class: "nav-link" do %>
          <i class="nav-icon fas fa-lock"></i>
          <%= t("layouts.sidebar.accounts.password") %>
        <% end %>
      <% end %>
      <%= nav_item controller: 'accounts/jwts', html_options: {class: "nav-item"} do %>
        <%= link_to account_jwts_path, class: "nav-link" do %>
          <i class="nav-icon fas fa-pencil-alt"></i>
          <%= t("layouts.sidebar.accounts.application") %>
        <% end %>
      <% end %>
    </ul>
  </nav>
  <button class="sidebar-minimizer" type="button"></button>
</div>

app/views/layouts/sidebars/_admin.html.erb
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <%= nav_item controller: 'admin/home', html_options: {class: "nav-item"} do %>
        <%= link_to admin_root_path, class: "nav-link" do %>
          <i class="nav-icon fas fa-tachometer-alt"></i>
          <%= t("layouts.sidebar.admin.home") %>
        <% end %>
      <% end %>
      <%= nav_item controller: 'admin/users', html_options: {class: "nav-item"} do %>
        <%= link_to admin_users_path, class: "nav-link" do %>
          <i class="nav-icon fas fa-user-circle"></i>
          <%= t("layouts.sidebar.admin.users") %>
        <% end %>
      <% end %>
    </ul>
  </nav>
  <button class="sidebar-minimizer" type="button"></button>
</div>

app/views/layouts/sidebars/_application.html.erb
<div class="sidebar">
  <div class="sidebar-header">
    <%= link_to root_path, class: "nav-link" do %>
      <i class="fas fa-home"></i>
      <%= t("layouts.sidebar.application.header") %>
    <% end %>
  </div>
  <nav class="sidebar-nav">
    <ul class="nav">
      <%= nav_item path: 'home#index', html_options: {class: "nav-item"} do %>
        <%= link_to root_path, class: "nav-link" do %>
          <i class="fas fa-tachometer-alt"></i>
          <%= t("layouts.sidebar.application.home") %>
        <% end %>
      <% end %>
    </ul>
  </nav>
  <button class="sidebar-minimizer" type="button"></button>
</div>